language: java
jdk:
- openjdk8

addons:
  sonarcloud:
    organization: "cecbazinga"
    token: "3a652adc6c42958cc6a7d600e769ab152b33ae08"



script:  mvn -B clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar 
